#%RAML 1.0
title: Loan Option API
description: Loan Option endpoint
version: 1.0.0
protocols:
  - HTTPS
  - HTTP
baseUri: https://mocksvc.mulesoft.com/mocks/40e8fdb7-7f15-4fdb-8fdd-84ac1e004a96 # baseUri: /
annotationTypes:
  oas-format:
    type: string
    allowedTargets: TypeDeclaration
  oas-body-name:
    type: string
    allowedTargets: TypeDeclaration
  oas-summary:
    type: string
    allowedTargets: Method
types:
  LoanOptions:
    type: array
    items: LoanOption
  LoanOption:
    type: object
    properties:
      dealId:
        example: 12345
        type: number
        (oas-format): int
      loanAmount:
        minimum: 1
        maximum: 10000000000000000
        example: 25000000
        type: number
        format: double
      Type:
        example: Ask
        type: string
      Status:
        example: Draft
        default: Draft
        type: string
        enum:
          - Draft
      Comments:
        minLength: 0
        maxLength: 200
        example: This is a comment.
        type: string
        required: false
      interestType:
        example: Variable Rate
        type: string
        enum:
          - Fixed Rate
          - Variable Rate
      variableProductType:
        required: false
        example: SARM
        enum: ["SARM","DMBS","ARM 7/6","ARM 7/4","Fixed+1",""]
      lienPosition:
        minimum: 1
        maximum: 3
        example: 1
        type: number
        (oas-format): int
      supplementalType:
        example: Coterminous
        type: string
        enum:
          - Coterminous
          - Non-Coterminous
          - DUS Split 2nd
          - New Loan Test
          - ""
        required: false
      exercisingTierDroppingOption:
        example: 'Yes'
        type: string
        enum:
          - 'Yes'
          - 'No'
          - ""
        required: false
      loanTermMonths:
        minimum: 1
        maximum: 480
        example: 120
        type: number
        (oas-format): int
      interestOnlyPeriodMonths:
        minimum: 0
        maximum: 480
        example: 24
        type: number
        (oas-format): int
      amortizationTermMonths:
        minimum: 1
        maximum: 480
        example: 360
        type: number
        (oas-format): int
      lossSharingPercent:
        minimum: 0
        maximum: 100
        example: 100
        type: number
        format: double
      prepaymentComponent1:
        example: Yield Maintenance
        type: string
        enum:
          - Yield Maintenance
          - Prepayment Lockout
          - Declining Premium
          - Defeasance
          - Defeasance Lockout
          - Fee Maintenance
          - Other Prepayment Premium
          - 1%  Fixed Prepayment
      prepaymentComponenttoMonths1:
        minimum: 0
        maximum: 480
        example: 174
        type: number
        (oas-format): int
      prepaymentComponent2:
        example: 1%  Fixed Prepayment
        type: string
        enum:
          - Yield Maintenance
          - Prepayment Lockout
          - Declining Premium
          - Defeasance
          - Defeasance Lockout
          - Fee Maintenance
          - Other Prepayment Premium
          - 1%  Fixed Prepayment
          - ""
        required: false
      prepaymentComponenttoMonths2:
        minimum: 0
        maximum: 480
        example: 177
        type: number
        (oas-format): int
        required: false
      decliningPremiumSchedule:
        example: 5-4-3-2-1-1-1-1-1-1
        type: string
        enum:
          - 5-4-3-2-1-1-1-1-1-1
          - 5-1-1-1-1-1-1-1-1-1
          - 5-4-3-2-1-1-1
          - 5-1-1-1-1-1-1
          - 5-4-3-2-1
          - 5-5-4-4-3-3-2-2-1-1
          - 10-10-5-4-3-2-1
          - 5-1-1-1-1
          - 5-5-5-5-4-4-3-3-2-2-1-1
          - 5-5-5-5-5-5-5-4-4-3-3-2-2-1-1
          - 5-5-5-5-5-5-5-4-4-3-3-2-2-1-1-1-1-1
          - 5-5-5-5-5-5-5-4-4-3-3-2-2-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1-1
          - ""
        required: false
      otherPrepaymentPremiumSchedule:
        example: 5-5-5-2-2-1-1-1-1-1
        type: string
        required: false
      propertyGrossPotentialRent:
        minimum: 0
        example: 2504467
        type: number
        format: double
      propertyEconomicVacancyAmount:
        example: -125223.35
        type: number
        format: double
      propertyOtherIncome:
        minimum: 0
        example: 40230.35
        type: number
        format: double
      propertyManagementFee:
        minimum: 0
        example: 60486.85
        type: number
        format: double
      propertyRealEstateTaxes:
        minimum: 0
        example: 190000
        type: number
        format: double
      propertyInsurance:
        minimum: 0
        example: 92788
        type: number
        format: double
      propertyOtherExpenses:
        minimum: 0
        example: 858736.15
        type: number
        format: double
      propertyReplacementReserves:
        minimum: 0
        example: 27000
        type: number
        format: double
      propertyActualCooperativeNCF:
        example: 85000
        type: number
        format: double
        required: false
      propertyPurchasePrice:
        minimum: 0
        example: 1500000
        type: number
        format: double
        required: false
      propertyCost:
        minimum: 0
        example: 1500000
        type: number
        format: double
        required: false
      propertyUnderwrittenValue:
        minimum: 0
        example: 15872826.67
        type: number
        format: double
      propertyUnitCount:
        minimum: 5
        example: 250
        type: number
        (oas-format): int
      x1stLienInterestType:
        example: Fixed Rate
        type: string
        enum:
          - Fixed Rate
          - Variable Rate
          - ""
        required: false
      x1stLienOriginalLoanAmount:
        example: 0
        type: number
        format: double
        required: false
      x1stLienActualFixedFixedEquivalentInterestRate:
        example: 0
        type: number
        format: double
        required: false
      x1stLienLoanTermMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      x1stLienInterestOnlyPeriodMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      x1stLienAmortizationTermMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      x1stLienVariableUWInterestRate:
        example: 0
        type: number
        format: double
        required: false
      x1stLienPurchasedCapStrikeRate:
        example: 0
        type: number
        format: double
        required: false
      x1stLienInterestBasis:
        example: Actual/360
        type: string
        enum:
          - Actual/360
          - 30/360
          - ""
        required: false
      x1stLienLoanMaturityDate:
        example: '1900-01-01'
        type: date-only
        required: false
      x1stLienCurrentUPBAmount:
        example: 0
        type: number
        format: double
        required: false
      x1stLienRequiredMinDSCRforLoanSizing:
        example: 0
        type: number
        format: double
        required: false
      x2ndLienInterestType:
        example: Fixed Rate
        type: string
        enum:
          - Fixed Rate
          - Variable Rate
          - ""
        required: false
      x2ndLienOriginalLoanAmount:
        example: 0
        type: number
        format: double
        required: false
      x2ndLienActualFixedFixedEquivalentInterestRate:
        example: 0
        type: number
        format: double
        required: false
      x2ndLienLoanTermMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      x2ndLienInterestOnlyPeriodMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      x2ndLienAmortizationTermMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      x2ndLienVariableUWInterestRate:
        example: 0
        type: number
        format: double
        required: false
      x2ndLienPurchasedCapStrikeRate:
        example: 0
        type: number
        format: double
        required: false
      x2ndLienInterestBasis:
        example: Actual/360
        type: string
        enum:
          - Actual/360
          - 30/360
          - ""
        required: false
      x2ndLienLoanMaturityDate:
        example: '1900-01-01'
        type: date-only
        required: false
      x2ndLienCurrentUPBAmount:
        example: 0
        type: number
        format: double
        required: false
      x2ndLienRequiredMinDSCRforLoanSizing:
        example: 0
        type: number
        format: double
        required: false
      pricingMethod:
        required: true
        example: Standard
        type: string
        enum:
          - Standard
          - Enhanced Standard
          - Tier Plus
          - Tier Plus/Plus
          - First Level Lender Delegated
          - Second Level Lender Delegated
      greenFinancingType:
        example: N/A
        type: string
        enum:
          - N/A
          - Green Rewards
          - Green Preservation Plus
          - 'Green Building Certification '
      latestPricingMemoGuarantyFee:
        example: 1.12
        type: number
        format: double
      latestPricingMemoServicingFee:
        example: 0.29
        type: number
        format: double
      commitmentPerioddays:
        example: 60
        type: number
        (oas-format): int
      rateLockType:
        example: Standard
        type: string
        enum:
          - Standard
          - Streamlined
      interestBasis:
        example: Actual/360
        type: string
        enum:
          - Actual/360
          - 30/360
      loanPurchasePriceofpar:
        example: 101
        type: number
        format: double
        required: false
      excessOriginationPremiumAmount:
        example: 0
        type: number
        format: double
        required: false
      estimatedOriginationFee:
        example: 0
        type: number
        format: double
        required: false
      originationFeePaidtoBroker:
        example: 0
        type: number
        format: double
        required: false
      originationFeePaidtoCorrespondent:
        example: 0
        type: number
        format: double
        required: false
      fixedIndexRateType:
        example: 10-Year Treasury Note
        type: string
        enum:
          - 1-Month Treasury Bill
          - 3-Month Treasury Bill
          - 6-Month Treasury Bill
          - 1-Year Treasury Note
          - 2-Year Treasury Note
          - 3-Year Treasury Note
          - 5-Year Treasury Note
          - 7-Year Treasury Note
          - 10-Year Treasury Note
          - 30-Year Treasury Note
      treasuryRate:
        example: 1.37
        type: number
        format: double
      totalFixedRateInvestorSpread:
        example: 1.39
        type: number
        format: double
      requestedFixedRateGuarantyFee:
        example: 0.9
        type: number
        format: double
      requestedFixedRateServicingFee:
        example: 0.21
        type: number
        format: double
      otherFixedRateFeeSpread:
        example: 0
        type: number
        format: double
      indexRateType:
        example: 1 Month LIBOR
        type: string
        enum:
          - 11 FHLB COFI (1 Month)
          - 11 FHLB COFI (6 Month)
          - 1 Year CMT Weekly Average Treasury
          - 3 Year CMT Weekly Average Treasury
          - 5 Year CMT Weekly Average Treasury
          - Wall Street Journal Prime Rate
          - 1 Month LIBOR
          - 3 Month LIBOR
          - 6 Month LIBOR
          - ""
        required: false
      indexRate:
        example: 0
        type: number
        format: double
        required: false
      totalVariableRateInvestorSpread:
        example: 0
        type: number
        format: double
        required: false
      requestedVariableRateGuarantyFee:
        example: 0
        type: number
        format: double
        required: false
      requestedVariableRateServicingFee:
        example: 0
        type: number
        format: double
        required: false
      capCostFactor:
        example: 0
        type: number
        format: double
        required: false
      underwrittenStressMaxLifetimePassThruRate:
        example: 0
        type: number
        format: double
        required: false
      sARMInitialCapTermMonths:
        example: 0
        type: number
        (oas-format): int
        required: false
      sARMMinCapStrikeRate:
        example: 0
        type: number
        format: double
        required: false
      uWInterestRateFloorperGuide:
        example: 3.87
        type: number
        format: double
        required: false
      guideTierLevel:
        example: Tier 4
        type: string
        enum:
          - Tier 2
          - Tier 3
          - Tier 4
          - ""
      guideMinActualCooperativeDSCR:
        example: 1
        type: number
        format: double
        required: false
      guideMinUWDSCRperGuide:
        example: 1.55
        type: number
        format: double
      guideMaximumLTV:
        example: 55
        type: number
        format: double
      guideFRTMinActualCooperativeDSCR:
        example: 0
        type: number
        format: double
        required: false
      guideFRTMinUWDSCRperGuide:
        example: 0
        type: number
        format: double
        required: false
      guideFRTLTV:
        example: 0
        type: number
        format: double
        required: false
      requestedTierLevel:
        example: Tier 4
        type: string
        enum:
          - Tier 2
          - Tier 3
          - Tier 4
          - ""
        required: false
      requestedMinActualCooperativeDSCR:
        example: 1
        type: number
        format: double
        required: false
      requestedMinUWDSCRperGuide:
        example: 5
        type: number
        format: double
      requestedMinAmortizingUWNCFDSCR:
        example: 1
        type: number
        format: double
      requestedMaximumLTV:
        example: 25
        type: number
        format: double
      requestedMaximumLTC?:
        example: 80
        type: number
        format: double
        required: false
      requestedFRTMinActualNCFCOOPDSCR:
        example: 0
        type: number
        format: double
        required: false
      requestedFRTMinUWDSCRperGuide:
        example: 0
        type: number
        format: double
        required: false
      requestedFRTMinAmortizingUWNCFDSCR:
        example: 0
        type: number
        format: double
        required: false
      requestedFRTLTV:
        example: 0
        type: number
        format: double
        required: false
      expectedExitRefinanceCosts:
        example: 0
        type: number
        format: double
        required: false
      expectedExitAmortizationTerm:
        example: 360
        type: number
        (oas-format): int
        required: false
      expectedExitMinUWDSCRperGuide:
        example: 1.25
        type: number
        format: double
        required: false
      expectedExitMaximumLTV:
        example: 80
        type: number
        format: double
        required: false
      expectedExitRefinanceInterestRate:
        example: 0
        type: number
        format: double
        required: false
      expectedExitTerminalCapRate:
        example: 0
        type: number
        format: double
        required: false
      mezzanineandPreferredEquityDebtService:
        example: 0
        type: number
        format: double
        required: false
      subordinateFinancing1:
        example: 0
        type: number
        format: double
        required: false
      subordinateFinancing2:
        example: 0
        type: number
        format: double
        required: false
      subordinateFinancing3:
        example: 0
        type: number
        format: double
        required: false
      mezzPreferredEquity1:
        example: 0
        type: number
        format: double
        required: false
      mezzPreferredEquity2:
        example: 0
        type: number
        format: double
        required: false
      lIHTCEquity:
        example: 0
        type: number
        format: double
        required: false
      otherSources:
        example: 0
        type: number
        format: double
        required: false
      payoffExistingMortgageLoan:
        example: 1088000
        type: number
        format: double
        required: false
      prepaymentPremium:
        example: 0
        type: number
        format: double
        required: false
      propertyDevelopmentConstructionCost:
        example: 0
        type: number
        format: double
        required: false
      affiliatedMezzanineDebtorPreferredEquityPayoff:
        example: 0
        type: number
        format: double
        required: false
      nonAffiliatedMezzanineDebtorPreferredEquityPayoff:
        example: 0
        type: number
        format: double
        required: false
      propertyFundedCapitalImprovements:
        example: 0
        type: number
        format: double
        required: false
      propertyFundedCapitalExpendituresReplacementReserveAccount:
        example: 0
        type: number
        format: double
        required: false
      propertyFundedCompletionRepairs:
        example: 0
        type: number
        format: double
        required: false
      propertyFundedOtherEscrows:
        example: 0
        type: number
        format: double
        required: false
      interestRateCapHedgingFees:
        example: 0
        type: number
        format: double
        required: false
      originationFees:
        example: 0
        type: number
        format: double
        required: false
      lenderClosingTransactionFees:
        example: 50000
        type: number
        format: double
        required: false
      thirdPartyClosingTransactionFees:
        example: 0
        type: number
        format: double
        required: false
      otherUses:
        example: 0
        type: number
        format: double
        required: false
/loanoption:
  post:
    description: Creates a new Loan Option
    displayName: addLoanOption
    responses:
      '201':
        description: Created
        body:
          application/json:
            type: object
            properties:
              loanOptionId:
                description: Loan Option Identifier
                type: string
    body:
      application/json:
        description: Loan Option Request
        type: LoanOptions
        (oas-body-name): body
    (oas-summary): Add a new Loan Option
